config/routes.rb
Rails.application.routes.draw do
  resources :users, only:[:show,:edit,:update,:create,:new]
  get 'signup' => 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :questions, except: [:destroy] do
    resources :answers, only: [:create, :edit, :update]
  end

  resources :comments, except: [:index, :show, :new]
  resources :votes, only: [:new, :create]
  resources :tags, only: [:show, :index]

  root :to => 'questions#index'

  get 'users/:id/questions' => 'users#search_in_questions'
  get 'questions/:id/answers' => 'questions#answers'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :body, :commentable_id, :commentable_type, :user_id, presence: :true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :find_comment

  def create
    if params[:answer_id]
      commentable = Answer.find_by(id: params[:answer_id])
    else
      commentable = Question.find_by(id: params[:question_id])
    end

    commentable.comments.build(body: params[:body], user_id: current_user.id)
    if !commentable.save
      flash[:warning] = "That was an invalid comment."
    end

    if request.xhr?
      respond_to do |format|
        format.html {render "comments/_comment", locals:{comment: commentable.comments.last}, layout: false}
      end
    else
      redirect_to :back
    end
  end

  def edit
  end

  def update
    if @comment.update_attributes(params[:comment])
      flash[:success] = "Comment updated."
      redirect_to question_path(@comment)
    else
      flash[:warning] = "That was an invalid comment."
      render :edit
    end
  end

  def destroy
    @comment.delete
    redirect_to :back
  end

  private

  def find_comment
    @comment = Comment.find_by(id: params[:id]) if params[:id]
  end
end

app/views/comments/_comment.html.erb
<div class="single-comment">
	<%= comment.body %> <br>
	&emsp;&emsp;-<em><%= comment.user.username %></em>
</div>

app/views/comments/_form.html.erb
<div class="comment-form">
  <%= form_tag comments_path do %>
    <div>
    <p><%= label_tag :body, "Type your comment here." %></p>
    <%= text_area_tag "body", nil, class: "comment-body" %>
    <%= hidden_field_tag "#{id_type}", id %>
    </div>
    <div>
    <%= submit_tag "Submit" %>
    </div>
  <% end %>
</div>