config/routes.rb
Rails.application.routes.draw do
  resources :users, only:[:show,:edit,:update,:create,:new]
  get 'signup' => 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :questions, except: [:destroy] do
    resources :answers, only: [:create, :edit, :update]
  end

  resources :comments, except: [:index, :show, :new]
  resources :votes, only: [:new, :create]
  resources :tags, only: [:show, :index]

  root :to => 'questions#index'

  get 'users/:id/questions' => 'users#search_in_questions'
  get 'questions/:id/answers' => 'questions#answers'
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :questions
	has_many :comments

	def questions_by(key, value)
		if(value)
			return questions.eager_load(:tags).where(["tags.tag_name LIKE ?","%#{value}%"]) if key == "tags"
			return questions.eager_load(:answers).where("answers.best_answer IS false or answers.question_id IS NULL") if key == "unanswered"
			questions.where([" title LIKE ?","%#{value}%"])
		else 
			questions
		end
	end

  validates :username, :email, :password, presence: :true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user
	before_filter :require_authentication, only:[:show,:edit,:update,:search_in_questions]
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			set_session_user @user.id
			redirect_to user_path(@user.id)
		else
			flash[:warning] = "Couldn't create a user"
			render :new
		end
	end

	def show
		@question_data = parse_questions @user.questions
	end

	def edit
	end

	def update
		@user.update_attributes(user_params)
		if @user.save
			redirect_to user_path(@user.id)
		else
			render :edit
		end
	end

	def search_in_questions
		respond_to do |format|
	    result = parse_questions @user.questions_by(params[:search_by],params[:description])
	    format.json  { render :json => result }
	  end		
	end

	private

	def set_user
		@user = User.find_by(id: params[:id])
	end

	def user_params
		params.require(:user).permit(:username,:email,:password)
	end

	def parse_questions (questions)
		questions.map do |question|
			Hash[question_id: question.id,
				title: question.title,
				answers: question.answers.count, 
				comments: question.comments.count, 
				votes: question.votes.count,
				karma: question.karma]
		end
	end

	def require_authentication
		redirect_to login_path unless ( is_authenticated? && (@user == current_user))
	end

end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon1">Username</span>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="input-group">
    <span class="input-group-addon" id="basic-addon1">Email</span>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="input-group">
    <span class="input-group-addon" id="basic-addon1">Password</span>
    <%= f.password_field :password, class: "form-control"%>
  </div>

  <div>
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h3>Update Profile <span class="label label-default"></span></h3>
<%= render 'form' %>

app/views/users/new.html.erb
Sign up
<%= render 'form' %>

app/views/users/show.html.erb
<div class="jumbotron">
  <h1><img id='profile-photo' src='http://www.gravatar.com/avatar/<%= gravitar(@user.email) %>'> Sup' <%= @user.username %></h1>
  <p><%= link_to "Ask a Question", new_question_path, class: "btn btn-primary btn-lg" %></p>
</div>

<div class="input-group">
	<span class="input-group-addon">Search by</span>
   <select class="form-control" id="search_by" name="search_by">
			<option value='title'>Title</option>
			<option value='tags'>Tags</option>
			<option value='unanswered'>Unaswered</option>
		</select> 
  <input id="description" type="text" class="form-control" placeholder="Description...">
  <span class="input-group-btn input-group-addon">
    <button class="btn btn-default" type="button" onclick="searchQuestion(<%=@user.id%>)" >search</button>
  </span>
</div>

<%= javascript_tag do %>
  var questions = <%=raw @question_data.to_json %>;
<% end %>

<hr>
<div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#list" aria-controls="list" role="tab" data-toggle="tab">List</a></li>
    <li role="presentation"><a href="#graph" aria-controls="graph" role="tab" data-toggle="tab">Graph</a></li>
     </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active graph_dimention" id="list">
      <div class='loading_container'><%= image_tag "loading.gif", class: "center" %></div>
    </div>
    <div role="tabpanel" class="tab-pane graph_dimention" id="graph">
      <div id="chart_div" class="graph_dimention"></div>
    </div>
      <div id="chart_nav" class="input-group"></div>
  
  </div>
</div>
<hr>

<div id="answers_container"></div>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script>loadGApi();</script>