config/routes.rb
Rails.application.routes.draw do
  resources :users, only:[:show,:edit,:update,:create,:new]
  get 'signup' => 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :questions, except: [:destroy] do
    resources :answers, only: [:create, :edit, :update]
  end

  resources :comments, except: [:index, :show, :new]
  resources :votes, only: [:new, :create]
  resources :tags, only: [:show, :index]

  root :to => 'questions#index'

  get 'users/:id/questions' => 'users#search_in_questions'
  get 'questions/:id/answers' => 'questions#answers'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :votes, as: :voteable
  has_many :comments, as: :commentable

  validates :body, :question_id, :user_id, presence: :true
  validates_uniqueness_of :question_id, scope: :user_id
  validate :different_user

  def karma
    all_votes = Vote.where(voteable_id: id, voteable_type: "Answer")
    all_votes.sum(:score)
  end

  private

  def different_user
    if self.user == self.question.user
      errors.add(:base, "You can't answer your own question.")
    end
  end
end

app/controllers/answer_controller.rb
class AnswerController < ApplicationController::Base
  before_filter :find_answer, :find_question

    def create
      @answer = Answer.new(answer_params)
      if @answer.save
        redirect_to question_path(@question)
      else
        flash[:warning] = "Could not save answerm please try again."
        render :new
      end
    end

    def edit
    end

    def update
      @question = params[:question_id]
      if @answer.update_attributes(params[:answer])
        flash[:success] = "Answer update saved"
        redirect_to question_path(@question)
      else
        flash[:warning] = "Unable to update answer"
        render :edit
      end
    end

    private

    def find_question
      @question = Question.find_by(id: params[:id]) if params[:id]
    end

    def find_answer
      @answer = Answer.find_by(id: params[:id]) if params[:id]
    end

    def answer_params
      params.require(:answer).permit(:body, :question_id).merge(user_id: current_user.id )
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :find_answer, except: [:create]

    def create
      @answer = Answer.new(answer_params)
      if !@answer.save
        flash[:warning] = "Could not save answer please try again."
      end
      if request.xhr?
        p "not a thing"
        respond_to do |format|
          format.html {render @answer, layout: false}
        end
      else
        redirect_to :back
      end
    end

    def edit
    end

    def update
        if @answer.update_attributes(answer_params)
        flash[:success] = "Answer update saved"
        redirect_to question_path(@answer.question)
      else
        flash[:warning] = "Unable to update answer"
        render :edit
      end
    end

    private

    def find_answer
      @answer = Answer.find_by(id: params[:id]) if params[:id]
    end

    def answer_params
      params.permit(:body, :question_id).merge(user_id: current_user.id )
    end
end

app/views/answers/_answer.html.erb
<div class="answer_partial">
  <p>Answer: <%= answer.body %></p>
  <p><em>User: <%= answer.user.username %></em></p>
  <p>Karma: <span class="karma"><%= answer.karma %></span></p>
</div>

<%= render partial:"votes/votes", locals: {type: "answer_id", id: answer.id} %>

<div class="edit_button">
<% if current_user.id == answer.user_id %>
  <%= link_to "Edit", edit_question_answer_path(answer.question_id, answer.id) %>
<% end %>
</div>
<div class="comment-section">
  <a class="toggle-comment-form" href="#">Comment</a>
  <%= render partial:"comments/form", locals: {id_type: "answer_id", id: answer.id}  %>
  <div class="comments">
    <%= render answer.comments %>
  </div>
</div>

app/views/answers/edit.html.erb
<%= form_tag question_answer_path(@answer.question.id, @answer.id), method: "put" do %>
  <div>
    <%= label_tag :body, "Answer" %><br>
    <%= text_area_tag :body, @answer.body %>
  </div>
  <div>
    <%= submit_tag 'Answer' %>
  </div>
<% end %>