config/routes.rb
Rails.application.routes.draw do
  resources :users, only:[:show,:edit,:update,:create,:new]
  get 'signup' => 'users#new'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  resources :questions, except: [:destroy] do
    resources :answers, only: [:create, :edit, :update]
  end

  resources :comments, except: [:index, :show, :new]
  resources :votes, only: [:new, :create]
  resources :tags, only: [:show, :index]

  root :to => 'questions#index'

  get 'users/:id/questions' => 'users#search_in_questions'
  get 'questions/:id/answers' => 'questions#answers'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<div class="navbar-brand"><%= link_to "Home", root_path  %></div>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<% if is_authenticated? %>
				<li><%= link_to "Profile",user_path(current_user.id) %></li>
				<li><%= link_to "Edit Profile",edit_user_path(current_user.id) %></li>
				<li><%= link_to "Logout",logout_path %></li>
				<% else %>
				<li><%= link_to "Sign up",signup_path %></li>
				<li><%= link_to "Login",login_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WindingsOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <%= render 'layouts/nav' %>
    <div class='msg'> <%= flash[:warning] %></div>
    <div class="container-yield">
    <%= yield %>
  </div>
</div>
</body>

</html>